- name: Anlominus RhytMix
  uses: lowlighter/metrics@v3.16

- uses: lowlighter/metrics@latest
  with:
    # ... other options
    plugin_reactions: yes
    plugin_reactions_limit: 200                  # Compute reactions over last 200 issue comments
    plugin_reactions_limit_issues: 100           # Compute reactions over last 100 issues/pull requests opened
    plugin_reactions_limit_discussions: 100      # Compute reactions over last 100 discussions
plugin_reactions_limit_discussions_comments: 100 # Compute reactions over last 100 discussions comments
    plugin_reactions_days: 14                    # Compute reactions on issue comments posted less than 14 days ago
    plugin_reactions_display: absolute           # Display percentages based on the total amoun fetched
    plugin_reactions_details: count, percentage  # Display reactions count and percentage
    plugin_reactions_ignored: bot                # Ignore "bot" user
