#!/bin/sh
#Shell菜单演示
#变量"configpath"的路径根据实际情况修改
basepath=$(cd `dirname $0`; pwd)
function menu ()
{
 cat << EOF
----------------------------------------
|***************菜单主页***************|
----------------------------------------
`echo -e "\033[47;30m 可以在任意选择界面按"Ctrl+c"键退出;脚本文件路径：$basepath\033[0m"`
`echo -e "\033[47;30m 1)Docker操作                                A)Iperf3\033[0m"`
`echo -e "\033[47;30m 2)Docker容器操作\033[0m"`
`echo -e "\033[47;30m 3)smokeping容器操作\033[0m"`
`echo -e "\033[47;30m 4)nmap操作\033[0m"`
`echo -e "\033[47;30m 5)Firewalld防火墙\033[0m"`
`echo -e "\033[47;30m 6)Iptables防火墙\033[0m"`
`echo -e "\033[47;30m 7)备份所有脚本到脚本目录的bak子目录\033[0m"`
`echo -e "\033[47;30m 8)创建menu别名\033[0m"`
`echo -e "\033[47;30m 9)vi 编译本脚本\033[0m"`
`echo -e "\033[47;30m 0)退出\033[0m"`
EOF
read -p "请输入功能对应的数字：" num1
while [ $num1 != '0' ];do
case $num1 in
 1)
   clear
   bash $basepath/menudocker
   exit 0
   ;;
 2)
   clear
   bash $basepath/menucontainer
   exit 0
   ;;
 3)
   clear
   bash $basepath/menusmokeping
   exit 0
   ;;
 4)
   clear
   bash $basepath/menunmap
   exit 0
   ;;
 5)
   clear
   bash $basepath/menufirewalld
   exit 0
   ;;
 6)
   clear
   bash $basepath/menuiptables
   exit 0
   ;;
 7)
   clear
   mkdir -p $basepath/bak
   cd $basepath
   tar czf $basepath/bak/bak.$(date "+%Y-%m-%d_%H-%M").tar menu*
   menu
   ;;
  8)
   clear
   echo -e "\033[47;30m 退出Shell再登录menu别名生效\033[0m"
   echo alias menu=\"bash $basepath/menu\" >> ~/.bashrc
   echo alias menu=\"bash $basepath/menu\" >> ~/.zshrc
   echo alias menu=\"bash $basepath/menu\" >> /etc/profile
   menu
   ;;
  9)
 vi $basepath/menu
 clear
 menu
  ;;
 a)
   clear
   bash $basepath/menuiperf3
   exit 0
   ;;
 0)
  exit 0
esac
done
}
menu
