#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
# Name : Anlominus
# Description : HacKingPro is a hacking tools installer and package manager for hacker's.
# New Date : 2022 January
# Last UPDATE : 2022 January 30
# Aouther: Anlominus RhytMix 2022
# Skils: Best Copyrigter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: ToAllWorldCreatorsHackingTools
# Location: Made With Love IN ISRAEL !
# Source: https://github.com/Anlominus/Anlominus
###############################################
chmod +x */*
##################################
#-----------) Colors (-----------#
##################################
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
###################################
#-----------) Letters (-----------#
###################################
# |
nr="R"
ni="I"
nt="T"
nx="X"
nq="Q"
na="A"
nb="ab"
n00="00"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n8="8"
n7="7"
n9="9"
n10="10"
n11="11"
n12="12"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"
# |
##########################
#    SymbolVariables     #
##########################
# |
cBack="$red[$cyan Back $red]$grey"
uSage="$red[$cyan USAGE $red]$grey("
installingDir="$red[$grey Installing Dir $red]$cyan"
# |
##########################
#    SymbolVariables     #
##########################
# 💪  🏴 ‍ ☠️ 👁‍ 👌 💀 📌 👍
# ♥️ ✯ 🔞 🗨 👩‍ 💻 😜 😡
# 💥 ☣ ✍ █ ▓ ░ ▒ 💿 🎧 📸
# 👤 🛠️ 📚 🌐 🐧 ❗ ✳️ 🛡️ 🎭 🖧
# ⚡ 🚶
cEye="$green 👁 $cyan"
cWall="$purple[$purple░$purple]$cyan"
cDock="$purple[$green📌$purple]$cyan"
cPassKey="$purple[$green🔐$purple]$cyan"
cAnlominus="$purple[$green👽$purple]$cyan"
cAlien="$purple[$green🙏$purple]$cyan"
cGlasses="$purple[$green👓$purple]$yellow"
cLock="$red[$yellow🔒$red]$grey"
cInvalid="$red[$yellow🚫$red]$red"
cKey="$red[$yellow🔑$red]$yellow"
cLink="$red[$orange🔗$red]$orange"
cSharp="$red[$yellow#$red]$blue"
cInfo="$red[$yellow!$red]$blue"
cPlus="$red[$green+$red]$white"
cDone="$red[$green✔$red]$green"
cFalse="$yellow[$red✘$yellow]$red"
cDanger="$yellow ⚠️ $red"
##########################
#    CommandVariables     #
##########################
# |
currentDir="${blue}Dir$orange $(pwd)"
SysInfo="${blue}SysInfo$orange $(uname)"
##########################
#    NumberVariables     #
##########################
# |
cr="$orange[$green$nr$orange]$grey"
ci="$orange[$green$ni$orange]$grey"
ct="$orange[$green$nt$orange]$grey"
cx="$orange[$green$nx$orange]$grey"
cq="$orange[$green$nq$orange]$grey"
ca="$orange[$green$na$orange]$grey"
cb="$orange[$green$nb$orange]$grey"
c1="$orange[$green$n1$orange]$cafe"
c2="$orange[$green$n2$orange]$cafe"
c3="$orange[$green$n3$orange]$cafe"
c4="$orange[$green$n4$orange]$cafe"
c5="$orange[$green$n5$orange]$cafe"
c6="$orange[$green$n6$orange]$cafe"
c7="$orange[$green$n7$orange]$cafe"
c8="$orange[$green$n8$orange]$cafe"
c9="$orange[$green$n9$orange]$cafe"
c10="$orange[$green$n10$orange]$cafe"
c11="$orange[$green$n11$orange]$cafe"
c12="$orange[$green$n12$orange]$cafe"
c13="$orange[$green$n13$orange]$cafe"
c14="$orange[$green$n14$orange]$cafe"
c15="$orange[$green$n15$orange]$cafe"
c16="$orange[$green$n16$orange]$cafe"
c17="$orange[$green$n17$orange]$cafe"
c18="$orange[$green$n18$orange]$cafe"
#####################################
#-----------) Functions (-----------#
#####################################
# |
BannerMan(){
  echo "$purple
                          .
                      ..',,'..
                    .',,,,,,,,,.
                   .',,,'..',,,,'.
                  .',,'.     .,,,'
                 .',,.        .,,,.
                .',..           .,,.
                .'.              ..,.
                .                  .'
               ..   $green  Aภl๏miภuຮ $purple   .
               ..                   .
               ..                  ...
        ....''''.   $blue HacKingPro$purple    .','''....
      .',,,,,,,,'..               ..',,,,,,,,'.
     ...'',,,,,,,'...          ....',,,,,,,,'...
    ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
   ......'',,;;;:::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/:'.
   .....'.'',,;;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/'....
   .......',,;;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/,......
   .'''''',,;;::/xxxxxxxxxx${cyan}DAT0S${purple}xxxxxxxxxxxx/,.......
  ..'''',',;;::/xxxxxxxxx${blue}ANL0M1NUS${purple}xxxxxxxxx/,'''''...
 ........';;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/:'.........
......  .':::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/::'..  ......
......:.;:::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/::;'c,':......
 .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''.
  \t ${orange}  ┌──[${blue}Anlominus${purple}@${red}HacKingPro${cyan}$~${orange}]
  \t ${orange}  └──╼ ${cyan} sh HacKingPro
  "
}
BannerAnlominus(){
  echo "
    _          _          __  __ _
   / \   _ __ | |    ___ |  \/  (_)_ __  _   _ ___
  / _ \ | '_ \| |   / _ \| |\/| | | '_ \| | | / __|
 / ___ \| | | | |__| (_) | |  | | | | | | |_| \__ \
/_/   \_\_| |_|_____\___/|_|  |_|_|_| |_|\__,_|___/
  "
}
Banner(){
  echo "
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall
  $cWall░     _   _            _  ___                 ░$cWall
  $cWall░    | | | | __ _  ___| |/ (_)_ __   __ _     ░$cWall
  $cWall░    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    ░$cWall
  $cWall░    |  _  | (_| | (__| . \| | | | | (_| |    ░$cWall
  $cWall░    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    ░$cWall
  $cWall░                                   |___/     ░$cWall
  $cWall▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒$cWall
  $cWall▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒$cWall
  $cWall▒           █   █  █ █  █ █   ▀▀█             ▒$cWall
  $cWall▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$orange v1.6        ${cyan}▒$cWall
  $cWall▒ https://www.github.com/Anlominus/HacKingPro ▒$cWall
  $cWall▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒$cWall"
}
Exiting(){
  echo "
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall
  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall
  $cWall░  ╠═>$cDanger Exiting Anlominus Tools...$cDanger${cyan} <==║  ░$cWall
  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
}
SourceCodeURL(){
  echo "\t  $cLink https://www.github.com/Anlominus/HacKingPro $cLink\n"
}
PromptFun(){
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  ${cWall}▓${orange}  ┌──[${blue}Anlominus${purple}👽${red}HacKingPro${cyan}$~${orange}]               ${cyan}▓$cWall"
  echo -n "  ${cWall}▓${orange}  └──╼ ${green} "
}
ReadSomthing(){
  echo "
$cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall
$cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall
$cWall▓  ╠═>   Press ENTER for back to Menu   <==║  ▓$cWall
$cWall▓  ╚═══════════════════════════════════════╝  ▓$cWall
$cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo -n ""
  read read_somthing
}
invalidFunction(){
  clear
  Banner
  echo ""
  echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
  echo "  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall"
  echo "  $cWall░  ╠═>      $cFalse invalid option!! $cFalse${cyan}    <==║  ░$cWall"
  echo "  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall"
  echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
  echo ""
  sleep 1
  clear
}
ALM_ClearHistory(){
  # Clear history run with sudo
  history -c
  cat /dev/null > /var/log/boot.log
  cat /dev/null > /var/log/cron
  cat /dev/null > /var/log/dmesg
  cat /dev/null > /var/log/firewalld
  cat /dev/null > /var/log/maillog
  cat /dev/null > /var/log/messages
  cat /dev/null > /var/log/spooler
  cat /dev/null > /var/log/syslog
  cat /dev/null > /var/log/tallylog
  cat /dev/null > /var/log/yum.log
}
while true; do
  clear
  Banner
  echo ""
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
  echo "  $cWall▓  ╠═>             Anlominus            <==║  ▓$cWall"
  echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
  echo "  $cWall▓  ╠═▶ ${ca} Anlominus                          ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶                                        ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶ ${ci} Install Core Tools                 ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶ ${cr} Remove Core Tools                  ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶ ${ct} TODO                               ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶ ${cb} About                             ${cyan}▓$cWall"
  echo "  $cWall▓  ╠═▶                                        ${cyan}▓$cWall"
  echo "  $cWall▓  ╚═➤ $cx Exit                               ${cyan}▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo ""
  PromptFun
  read cmd
  case ${cmd} in
    a|A)
    clear
    Banner
    echo "  ${cWall}▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓${cWall}"
    echo "  ${cWall}▓                                             ▓${cWall}"
    echo "  ${cWall}▓  ╔═══════════════════════════════════════╗  ${cWall}"
    echo "  ${cWall}▓  ╠═> 👽          Anlominus         👽 <==║  ${cWall}"
    echo "  ${cWall}▓  ╠═══════════════════════════════════════╝  ${cWall}"
    echo "  ${cWall}▓  ╚═➤  $cAnlominus Anlominus Tools $cAnlominus    ${cWall} "
    echo ""
    chmod +x "AnlominusKit"
    sh "AnlominusKit"
    sleep 1
    ;;
    i|install|I|Install)
    clear
    Banner
    # Information
    echo "  ${cWall}  ╔═══════════════════════════════════════╗  ${cWall}"
    echo "  ${cWall}  ╠═>             Anlominus            <==║  ${cWall} "
    echo "  ${cWall}  ╠═══════════════════════════════════════╝  ${cWall} "
    sleep 1
    echo "  ${cWall}  ╠═▶ Creating $grey AnlominusCore"
    sleep 1
    mkdir "AnlominusCore"
    cd "AnlominusCore"
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Anonymity"
    mkdir "00 - Anonymity"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Information Gathering"
    mkdir "01 - Information Gathering"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Vulnerability Analysis"
    mkdir "02 - Vulnerability Analysis"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Web Application Analysis"
    mkdir "03 - Web Application Analysis"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Database Assessment"
    mkdir "04 - Database Assessment"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Password Attacks"
    mkdir "05 - Password Attacks"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey WireLess Attacks"
    mkdir "06 - Wireless Attacks"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Reverse Engineering"
    mkdir "07 - Reverse Engineering"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Expliot Frameworks"
    mkdir "08 - Exploit Frameworks"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Sniffing - Spoofing"
    mkdir "09 - Sniffing - Spoofing"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Maintaining Access"
    mkdir "10 - Maintaining Access"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Forensic"
    mkdir "11 - Forensic"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Reporting"
    mkdir "12 - Reporting"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Social Engineering"
    mkdir "13 - Social Engineering"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Privilege Escalation"
    mkdir "14 - Privilege Escalation"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Malware Analysis"
    mkdir "15 - Malware Analysis"
    sleep 1
    # Information
    echo "  ${cWall}  ╠═▶ Creating $grey Covering Tracks"
    mkdir "16 - Covering Tracks"
    sleep 1
    # Information
    echo "  ${cWall}  ╚═▶ ${currentDir}"
    ReadSomthing
    # chmod +x Install
    # sh Install
    ;;
    r|remove|R|Remove)
    clear
    Banner
    if [ -e AnlominusCore ]; then
      #statements
      echo "  ${cWall}  ╔═══════════════════════════════════════╗  ${cWall}"
      echo "  ${cWall}  ╠═>             Anlominus            <==║  ${cWall}"
      echo "  ${cWall}  ╠═══════════════════════════════════════╝  ${cWall}"
      sleep 0.5
      echo "  ${cWall}  ╠═➤ ${cInfo} Found AnlominusCore....            ${cWall}"
      sleep 1.5
      echo "  ${cWall}  ╠═➤ $cDanger Removing Anlominus Tools....       ${cWall}"
      sleep 2
      `rm -R AnlominusCore*`
      echo "  ${cWall}  ╚═➤ $cDone Removing Complete....              ${cWall}"
      sleep 2
    else
      clear
      Banner
      echo "  $cFalse  ╔═══════════════════════════════════════╗  $cFalse "
      echo "  $cFalse  ╠═>             Anlominus            <==║  $cFalse "
      echo "  $cFalse  ╠═══════════════════════════════════════╝  $cFalse "
      echo "  $cFalse  ╚═➤ $cFalse AnlominusCore not exist... $cFalse     $cFalse "
      sleep 1.5
    fi
    ;;
    t|todo|T|TODO)
    chmod +x TODO
    sh TODO
    ;;
    x|X|exit|Exit)
    clear
    Banner
    Exiting
    sleep 0.3
    echo ""
    break
    ;;
    ab|about|About)
    clear
    Banner
    echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
    echo "  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall"
    echo "  $cWall░  ╠═>      $cFalse About Anlominus $cFalse     <==║  ░$cWall"
    echo "  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall"
    echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
    echo ""
    chmod +x "About"
    sh "About"
    ;;
    1)
    chmod +x CheckOS
    sh CheckOS
    ;;
    *)
    invalidFunction
    ;;
  esac
done
