#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
# Name : AnlominusVariables
# Description : HacKingPro is a hacking tools installer and package manager for hacker's.
# New Date : 2022 January
# Aouther: Anlominus RhytMix 2022
# Skils: Best Copyrigter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: ToAllWorldCreatorsHackingTools
# Location: Made With Love IN ISRAEL !
# Source: https://github.com/Anlominus/Anlominus
###############################################
# |
##################################
#-----------) Colors (-----------#
##################################
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
blueBG="\033[44m"
orange="\033[38;5;202m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
###################################
#-----------) Letters (-----------#
###################################
# |
nair="air"
nsr="sr"
nr="R"
ni="I"
nt="T"
nx="X"
nq="Q"
na="A"
nb="ab"
n00="00"
n0="0"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n8="8"
n7="7"
n9="9"
n10="10"
n11="11"
n12="12"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"
# |
##########################
#    Words Variables     #
##########################
# |
cNotFound="$red[${orange}Not Found${red}]$grey"
cFound="$red[${orange}Found${red}]$grey"
cBack="$red[$cyan Back $red]$grey"
uSage="$red[$cyan USAGE $red]$grey("
installingDir="$red[$grey Installing Dir $red]$cyan"
# |
#############################
#    Symbolls Variables     #
#############################
# 💪 ☠️ 🚶
# 🗨 👩‍ 💻 😜 😡
# 💥 ✍ █ ▓ ░ ▒ 💿 🎧 📸
# 👤 ️📚 🌐 ❗ ✳️ 🛡️ 🎭
cEye="$green 👁 $cyan"
cStar="$orange[$red✯$orange]$cyan"
cWell="$orange[$red👌$orange]$cyan"
cPin="$orange[$red📌$orange]$cyan"
cNetworks="$orange[$red🖧$orange]$cyan"
cWorld="$orange[$red🌐$orange]$cyan"
cToxic="$orange[$red☣$orange]$cyan"
cHeart="$orange[$red♥️$orange]$cyan"
cTools="$orange[$red🛠$orange]$cyan"
cLike="$orange[$red👍$orange]$cyan"
cElectric="$orange[$red⚡$orange]$cyan"
cSkull="$orange[$red💀$orange]$cyan"
cFlag="$orange[$red🏴$orange]$cyan"
c18Plus="$orange[$red🔞$orange]$cyan"
cWall="$purple[$purple░$purple]$cyan"
cDock="$purple[$green📌$purple]$cyan"
cPassKey="$purple[$green🔐$purple]$cyan"
cAnlominus="$purple[$green👽$purple]$cyan"
cAlien="$purple[$green🙏$purple]$cyan"
cGlasses="$purple[$green👓$purple]$yellow"
cLock="$red[$yellow🔒$red]$grey"
cInvalid="$red[$yellow🚫$red]$red"
cKey="$red[$yellow🔑$red]$yellow"
cLink="$red[$orange🔗$red]$orange"
cSharp="$red[$yellow#$red]$blue"
cInfo="$red[$yellow!$red]$cyan"
cPlus="$red[$green+$red]$white"
cDone="$red[$green✔$red]$green"
cFalse="$yellow[$red✘$yellow]$red"
cDanger="$yellow ⚠️ $red"
# |
#############################
#    Commands Variables     #
###############$$############
# |
currentDir="${blue}Dir$orange $(pwd)"
SysInfo="${blue}SysInfo$orange $(uname)"
# |
############################
#    Numbers Variables     #
############################
# |
cair="$orange[$green$nair$orange]$grey"
csr="$orange[$green$nsr$orange]$grey"
cr="$orange[$green$nr$orange]$grey"
ci="$orange[$green$ni$orange]$grey"
ct="$orange[$green$nt$orange]$grey"
cx="$orange[$green$nx$orange]$grey"
cq="$orange[$green$nq$orange]$grey"
ca="$orange[$green$na$orange]$grey"
cb="$orange[$green$nb$orange]$grey"
c0="$orange[$green$n0$orange]$cafe"
c1="$orange[$green$n1$orange]$cafe"
c2="$orange[$green$n2$orange]$cafe"
c3="$orange[$green$n3$orange]$cafe"
c4="$orange[$green$n4$orange]$cafe"
c5="$orange[$green$n5$orange]$cafe"
c6="$orange[$green$n6$orange]$cafe"
c7="$orange[$green$n7$orange]$cafe"
c8="$orange[$green$n8$orange]$cafe"
c9="$orange[$green$n9$orange]$cafe"
c10="$orange[$green$n10$orange]$cafe"
c11="$orange[$green$n11$orange]$cafe"
c12="$orange[$green$n12$orange]$cafe"
c13="$orange[$green$n13$orange]$cafe"
c14="$orange[$green$n14$orange]$cafe"
c15="$orange[$green$n15$orange]$cafe"
c16="$orange[$green$n16$orange]$cafe"
c17="$orange[$green$n17$orange]$cafe"
c18="$orange[$green$n18$orange]$cafe"
# |

#####################################
#-----------) Functions (-----------#
#####################################
# |
Banner(){
  echo "
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall
  $cWall░     _   _            _  ___                 ░$cWall
  $cWall░    | | | | __ _  ___| |/ (_)_ __   __ _     ░$cWall
  $cWall░    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    ░$cWall
  $cWall░    |  _  | (_| | (__| . \| | | | | (_| |    ░$cWall
  $cWall░    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    ░$cWall
  $cWall░                                   |___/     ░$cWall
  $cWall▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒$cWall
  $cWall▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒$cWall
  $cWall▒           █   █  █ █  █ █   ▀▀█             ▒$cWall
  $cWall▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$orange v1.6        ${cyan}▒$cWall
  $cWall▒ https://www.github.com/Anlominus/HacKingPro ▒$cWall
  $cWall▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒$cWall
  "
}
Exiting(){
  echo "
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall
  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall
  $cWall░  ╠═>$cDanger Exiting Anlominus Tools...$cDanger${cyan} <==║  ░$cWall
  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall
  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall
  "
}
PromptFun(){
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  ${cWall}▓${orange}  ┌──[${blue}Anlominus${purple}@${red}IptablesRules${cyan}$~${orange}]             ${cyan}▓$cWall"
  echo -n "  ${cWall}▓${orange}  └──╼ ${green}"
}
ReadSomthing(){
  echo "
  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall
  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall
  $cWall▓  ╠═>   Press ENTER for back to Menu   <==║  ▓$cWall
  $cWall▓  ╚═══════════════════════════════════════╝  ▓$cWall
  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall
  "
  echo -n ""
  read read_somthing
}
Banner
IptablesAllowRules(){
  while true; do
    clear
    Banner
    echo ""
    echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
    echo "  $cWall▓                                             ▓$cWall"
    echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
    echo "  $cWall▓  ╠═>       Allow IpTables Rules       <==║  ▓$cWall"
    echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
    echo "  $cWall▓  ╠═▶ ${ca} Anlominus"
    echo "  $cWall▓  ╠═▶ ${csr} Saving Rules"
    echo "  $cWall▓  ╠═▶ "
    echo "  $cWall▓  ╠═▶ ${c0} Established and Related Incoming Connections"
    echo "  $cWall▓  ╠═▶ ${c1} Established Outgoing Connections"
    echo "  $cWall▓  ╠═▶ ${c2} Loopback Connections"
    echo "  $cWall▓  ╠═▶ ${c3} SMTP"
    echo "  $cWall▓  ╠═▶ ${c4} IMAP"
    echo "  $cWall▓  ╠═▶ ${c5} IMAPS"
    echo "  $cWall▓  ╠═▶ ${c6} POP3"
    echo "  $cWall▓  ╠═▶ ${c7} POP3S"
    echo "  $cWall▓  ╠═▶ ${c8} SSH"
    echo "  $cWall▓  ╠═▶ ${c9} HTTP"
    echo "  $cWall▓  ╠═▶ ${c10} HTTPS"
    echo "  $cWall▓  ╠═▶ "
    echo "  $cWall▓                                             ▓$cWall"
    echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
    PromptFun
    read cmd
    case ${cmd} in
      0)
      echo "  ${cInfo} Allow Established and Related Incoming Connections"
      iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      ;;
      1)
      echo "  ${cInfo} Allow Established Outgoing Connections"
      iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ;;
      2)
      echo "  ${cInfo} Allow Loopback Connections"
      iptables -A INPUT -i lo -j ACCEPT
      iptables -A OUTPUT -o lo -j ACCEPT
      ReadSomthing
      ;;
      3)
      echo "  ${cInfo} Allow All Incoming SMTP"
      iptables -A INPUT -p tcp --dport 25 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 25 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ReadSomthing
      ;;
      4)
      echo "  ${cInfo} Allow All Incoming IMAP"
      iptables -A INPUT -p tcp --dport 143 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 143 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ReadSomthing
      ;;
      5)
      echo "  ${cInfo} Allow All Incoming IMAPS"
      iptables -A INPUT -p tcp --dport 993 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 993 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ReadSomthing
      ;;
      6)
      echo "  ${cInfo} Allow All Incoming POP3"
      iptables -A INPUT -p tcp --dport 110 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 110 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ReadSomthing
      ;;
      7)
      echo "  ${cInfo} Allow All Incoming POP3S"
      iptables -A INPUT -p tcp --dport 995 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 995 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ReadSomthing
      ;;
      8)
      echo "  ${cInfo} Allow All Incoming SSH"
      iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ;;
      9)
      echo "  ${cInfo} Allow All Incoming HTTP"
      iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ;;
      10)
      echo "  ${cInfo} Allow All Incoming HTTPS"
      iptables -A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A OUTPUT -p tcp --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ;;
      x|X|exit|Exit)
      clear
      Banner
      Exiting
      sleep 0.3
      echo ""
      break
      ;;
      *)
      clear
      Banner
      echo ""
      echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
      echo "  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall"
      echo "  $cWall░  ╠═>      $cFalse invalid option!! $cFalse${cyan}    <==║  ░$cWall"
      echo "  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall"
      echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
      echo ""
      sleep 1
      clear
      ;;
    esac
  done
}
while true; do
  clear
  Banner
  echo ""
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
  echo "  $cWall▓  ╠═>       List IpTables Rules        <==║  ▓$cWall"
  echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
  echo "  $cWall▓  ╠═▶ ${ca} Anlominus"
  echo "  $cWall▓  ╠═▶ ${c1} Saving Rules"
  echo "  $cWall▓  ╠═▶ ${cair} Allow Rules"
  echo "  $cWall▓  ╠═▶ ${c2} List all rules"
  echo "  $cWall▓  ╠═▶ ${c3} List all rules numeric and verbose"
  echo "  $cWall▓  ╠═▶ ${c4} Print out all of the active iptables rules"
  echo "  $cWall▓  ╠═▶ ${c5} List Rules as Tables for INPUT chain"
  echo "  $cWall▓  ╠═▶ ${c6} Print all of the rule specifications in the INPUT chain"
  echo "  $cWall▓  ╠═▶ ${c7} Show Packet Counts and Aggregate Size"
  echo "  $cWall▓  ╠═▶ ${c8} Display INPUT/OUTPUT chain rules withs numeric lines and verbose"
  echo "  $cWall▓  ╠═▶ "
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
  echo "  $cWall▓  ╠═>       Delete IpTables Rules      <==║  ▓$cWall"
  echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
  echo "  $cWall▓  ╠═▶ ${c9} Delete INPUT Rule by Chain and Number"
  echo "  $cWall▓  ╠═▶ ${c10} Delete FORWARD Rule by Chain and Number"
  echo "  $cWall▓  ╠═▶ ${c11} Delete OUTPUT Rule by Chain and Number"
  echo "  $cWall▓  ╠═▶ "
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
  echo "  $cWall▓  ╠═>       Flush IpTables Rules       <==║  ▓$cWall"
  echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
  echo "  $cWall▓  ╠═▶ ${c12} Flush All Rules, Delete All Chains, and Accept All"
  echo "  $cWall▓  ╠═▶ "
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓  ╔═══════════════════════════════════════╗  ▓$cWall"
  echo "  $cWall▓  ╠═>        Allow IpTables Rules      <==║  ▓$cWall"
  echo "  $cWall▓  ╠═══════════════════════════════════════╝  ▓$cWall"
  echo "  $cWall▓  ╠═▶ ${c9} Allow All Incoming SSH"
  echo "  $cWall▓  ╠═▶ ${c10} Allow Incoming SSH from Specific IP address or subnet"
  echo "  $cWall▓  ╠═▶ ${c11} Allow Outgoing SSH"
  echo "  $cWall▓  ╠═▶ "
  echo "  $cWall▓  ╚═➤ $cx Exit                               ${cyan}▓$cWall"
  echo "  $cWall▓                                             ▓$cWall"
  echo "  $cWall▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓$cWall"
  echo ""
  PromptFun
  read cmd
  case ${cmd} in
    air)
    IptablesAllowRules
    ;;
    a|A)
    ../../../Anlominus
    ;;
    1|save)
    echo "  ${cWall}  ╔═══════════════════════════════════════╗  ${cWall}"
    echo "  ${cWall}  ╠═>          Saving Rules            <==║  ${cWall}"
    echo "  ${cWall}  ╠═══════════════════════════════════════╝  ${cWall}"
    echo "  ${cWall}  ╠═>         ${c1} Debian             <==║  ${cWall}"
    echo "  ${cWall}  ╠═>         ${c2} RedHat             <==║  ${cWall}"
    sleep 0.5
    echo "  ${cInfo} Debian Based"
    sleep 1
    netfilter-persistent save
    echo "  ${cInfo} RedHat Based"
    sleep 1
    service iptables save
    ;;
    2)
    echo "
    ${cInfo} List out all of the active iptables rules with verbose
    "
    sleep 1
    iptables -n -L -v
    ReadSomthing
    ;;
    3)
    echo "
    ${cInfo} List out all of the active iptables rules with numeric lines and verbose
    "
    iptables -n -L -v --line-numbers
    ReadSomthing
    ;;
    4)
    echo "
    ${cInfo} Print out all of the active iptables rules
    "
    iptables -S
    ReadSomthing
    ;;
    5)
    echo "
    ${cInfo} List Rules as Tables for INPUT chain
    "
    iptables -L INPUT
    ReadSomthing
    ;;
    6)
    echo "
    ${cInfo} Print all of the rule specifications in the INPUT chain
    "
    iptables -S INPUT
    ReadSomthing
    ;;
    7)
    echo "
    ${cInfo} Show Packet Counts and Aggregate Size
    "
    iptables -L INPUT -v
    ReadSomthing
    ;;
    8)
    echo "
    ${cInfo} Display INPUT/OUTPUT chain rules withs numeric lines and verbose
    "
    iptables -L INPUT -n -v --line-numbers
    iptables -L OUTPUT -n -v --line-numbers
    ReadSomthing
    ;;
    9)
    echo "  ${cInfo} Delete INPUT Rule by Chain and Number"
    echo -n "  ${cInfo} Enter Rule Number: "
    read DeleteRuleNumber
    iptables -D INPUT ${DeleteRuleNumber}
    ReadSomthing
    ;;
    10)
    echo "  ${cInfo} Delete FORWARD Rule by Chain and Number"
    echo -n "  ${cInfo} Enter Rule Number: "
    read DeleteRuleNumber
    iptables -D FORWARD ${DeleteRuleNumber}
    ReadSomthing
    ;;
    11)
    echo "  ${cInfo} Delete OUTPUT Rule by Chain and Number"
    echo -n "  ${cInfo} Enter Rule Number: "
    read DeleteRuleNumber
    iptables -D OUTPUT ${DeleteRuleNumber}
    ReadSomthing
    ;;
    12)
    echo "  ${cInfo} Flush All Rules, Delete All Chains, and Accept All"
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT

    iptables -t nat -F
    iptables -t mangle -F
    iptables -F
    iptables -X
    ReadSomthing
    ;;
    13)

    ReadSomthing
    ;;
    14)
    echo "  ${cInfo} Flush a Single Chain"
    echo -n "  ${cInfo} Enter INPUT or FORWARD or OUTPUT: "
    read DeleteRuleName
    iptables -F ${DeleteRuleName}
    ReadSomthing
    ;;
    x|X|exit|Exit)
    clear
    Banner
    Exiting
    sleep 0.3
    echo ""
    break
    ;;
    *)
    clear
    Banner
    echo ""
    echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
    echo "  $cWall░  ╔═══════════════════════════════════════╗  ░$cWall"
    echo "  $cWall░  ╠═>      $cFalse invalid option!! $cFalse${cyan}    <==║  ░$cWall"
    echo "  $cWall░  ╚═══════════════════════════════════════╝  ░$cWall"
    echo "  $cWall░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░$cWall"
    echo ""
    sleep 1
    clear
    ;;
  esac
done
